version: '3'

services:
  localstack:
    image: localstack/localstack
    container_name: ${LOCALSTACK_DOCKER_NAME-localstack_main}
    network_mode: bridge
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=serverless,events
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOVE_CONTAINERS=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
